name: Build/release

# on:
#   push:
#     branches:
#       - main

on: push

jobs:
  release:
    if: github.ref == 'refs/heads/main'
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        # uses: actions/checkout@v1
        uses: actions/checkout@v4

      - name: Install Node.js, NPM and Yarn
        # uses: actions/setup-node@v1
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Build/release Electron app
        # uses: samuelmeuli/action-electron-builder@v1
        uses: jsoma/action-electron-forge@v1
        with:
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ secrets.github_token }}

          # If the commit is tagged with a version (e.g. "v1.0.0"),
          # release the app after building
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
